### ISSUE TITLE
Convert Video to Text

### ISSUE THREAD

**Issue by Miguel-Enrique13** [MLH-Fellowship/ClipBit#1]
Use [Google Cloud Speech-to-Text API](https://cloud.google.com/speech-to-text/docs/async-time-offsets#speech_transcribe_async_word_time_offsets_gcs-protocol) to convert Video to Text file. 

- [x] Read the [Google Cloud Speech-to-Text API](https://cloud.google.com/speech-to-text/docs/async-time-offsets#speech_transcribe_async_word_time_offsets_gcs-protocol) documentation.
- [x] Import video from CLI #4
- [x] Test that Text block has been created

**Comment by gmelodie** [comment]
One thing to keep in mind: API rate limiting
